name: HunterGames
author: SideEffect
version: 0.3
main: me.sideeffect.huntergames.HunterGames
depend: [MessageBarAPI,]
softdepend: [LibsDisguises,]
commands:
   help:
     description: Help command
     aliases: [?, hlp, ls]
   create:
     description: Set the lobby for after each game
     aliases: [c, cr, crate, creat, cret]
   setlobby:
     description: Set the lobby for after each game
     aliases: [setlob, sl]
   setspawn:
     description: Set spawns for arenas
     aliases: [setsp, ss]
permissions:
   huntergames.*:
     description: All HunterGames commands under 1 permission
     default: false
     children:
       huntergames.admin: true
   huntergames.admin:
     description: All admin permissions
     default: false